DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, FIRST_NAME VARCHAR(255), MIDDLE_NAME VARCHAR(255), LAST_NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
    GENRE_ID BIGINT NOT NULL,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);

