spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  message: "Test Props msg"
  locale: ru_RU
  hello-output: "Hello, {0}!"

test:
  passing-threshold: 3
  excellent-message: "Congratulations, you are excellent passed the test (right {0} from 5)"
  satisfactory-message: "You are passed the test, but you can do it better (right {0} from 5)"
  good-message: "You are passed the test, good result (right {0} from 5)"
  failure-message: "You are not passed test, please try again (right {0} from 5)"
  mark:
    bad: 2
    satisfactory: 3
    good: 4
    excellent: 5
