DROP SEQUENCE IF EXISTS SEQ_BOOK_ID;
CREATE SEQUENCE SEQ_BOOK_ID ;

DROP SEQUENCE IF EXISTS SEQ_AUTHOR_ID;
CREATE SEQUENCE SEQ_AUTHOR_ID ;

DROP SEQUENCE IF EXISTS SEQ_GENRE_ID;
CREATE SEQUENCE SEQ_GENRE_ID ;

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT auto_increment PRIMARY KEY, FIRST_NAME VARCHAR(255), MIDDLE_NAME VARCHAR(255), LAST_NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255) UNIQUE);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT auto_increment PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
    GENRE_ID BIGINT NOT NULL,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(ID BIGINT auto_increment PRIMARY KEY,
    COMMENT VARCHAR(255),
    BOOK_ID BIGINT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(ID BIGINT auto_increment PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    ENABLED BOOLEAN);

DROP TABLE IF EXISTS AUTHORITIES;
CREATE TABLE AUTHORITIES( USERNAME VARCHAR(255), AUTHORITY VARCHAR(255));



